package de.fsiebecke.ShowcaseAppBackend.plugins
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable
import java.time.LocalDateTime

@Serializable
data class DeviceDataModel(
    val dataModelVersion: Int,
    val deviceId: String,
    @Contextual val lastLoginDateTime: LocalDateTime? = null,
    val anonymizePersonalData: Boolean? = null,
    val primaryUserName: String,
    val accountSorting: AccountSortingEnum? = null,
    val allowFirebaseTracking: Boolean? = null,
    val appId: Int? = null,
    val appLanguage: String? = null,
    val appLoginMode: LoginModeEnum? = null,
    val appTheme: AppThemeEnum? = null,
    val appVariant: String? = null,
    val appVersion: Int? = null,
    val autoUpdateBalance: Boolean? = null,
    val maxSessionDuration: Int? = null,
    val deviceModel: String? = null,
    val deviceTheme: AppThemeEnum? = null,
    val os: String? = null,
    val osVersion: String? = null,
    val otherRedApps: List<String?>? = null,
    val physicalDeviceId: String? = null,
    val systemLanguage: String? = null,
    val allowAccountAlarmNotifications: Boolean? = null,
    val allowIndividualOffersNotifications: Boolean? = null,
    val allowNotificationBadge: Boolean? = null,
    val allowSystemNotifications: Boolean? = null,
    @Contextual val lastPingNotificationReceivedDateTime: LocalDateTime? = null,
    val pushToken: String? = null,
    val numberOfMbfAccounts: Int? = null,
    val numberOfMkaAccounts: Int? = null,
    val numberOfOtherAccounts: Int? = null,
    val numberOfSavingBanks: Int? = null,
    val numberOfSavingBanksAccounts: Int? = null,
    val quickAccessButtons: List<QuickAccessButtonsEnum>? = null,
    val featuresRequiringAttention: List<UsageFeatureEnum>? = null,
    val frequentlyUsedFeatures: List<UsageFeatureEnum>? = null,
    val subscribedToAloha: Boolean? = null,
    val subscribedToBudgetBook: Boolean? = null,
    val subscribedToDiamond: Boolean? = null,
    val subscribedToKwitt: Boolean? = null,
    val subscribedToWero: Boolean? = null,
)
