package de.fsiebecke.ShowcaseAppBackend

val testData = listOf(
    """{
        "deviceId": "123e4567-e89b-12d3-a456-426614174000",
        "primaryUserName": "fantasyUser123",
        "accountSorting": "ACCOUNTHOLDER",
        "autoUpdateBalance": true,
        "appId": 42,
        "appLanguage": "en-US",
        "maxSessionDuration": 3600,
        "appTheme": "DARK",
        "appVariant": "premium",
        "appVersion": 120,
        "appLoginMode": "BIOMETRIC",
        "allowFirebaseTracking": false,
        "deviceModel": "MagicPhone X200",
        "deviceTheme": "LIGHT",
        "otherRedApps": ["AppOne", "AppTwo", "AppThree"],
        "osVersion": "MagicOS 15.3",
        "physicalDeviceId": "abcdef1234567890",
        "systemLanguage": "de-DE",
        "incomeExpenseWidgetVariant": true,
        "offerAroundTheProperty": false,
        "offerClick2Credit": true,
        "offerMoneyBoxFieldTesting": true,
        "offerPrivateBanking": false,
        "requireReviewPersonalData": true,
        "requireTermsConditionsAgreement": true,
        "sendDynatraceBeacons": false,
        "allowAccountAlarmNotifications": true,
        "allowIndividualOffersNotifications": true,
        "allowNotificationBadge": true,
        "allowSystemNotifications": true,
        "lastPingNotificationReceivedDateTime": "2024-11-12T18:42:04",
        "pushToken": "pushToken_example_12345",
        "fullAppStartsMsSinceLastCommit": 100000,
        "fullAppStartsSinceLastCommit": 15,
        "lastLoginDateTime": "2024-11-11T09:15:27",
        "numberOfMbfAccounts": 3,
        "numberOfMkaAccounts": 1,
        "numberOfOtherAccounts": 2,
        "numberOfSavingBanks": 2,
        "numberOfSavingBanksAccounts": 5,
        "subsequentAppStartsMsSinceLastCommit": 50000,
        "subsequentAppStartsSinceLastCommit": 7,
        "frequentlyUsedFeatures": ["INCOGNITO", "PHOTO_TRANSFER"],
        "featuresRequiringAttention": ["REVIEW"],
        "subscribedToAloha": true,
        "subscribedToBudgetBook": false,
        "subscribedToDiamond": true,
        "subscribedToKwitt": false,
        "subscribedToWero": true,
        "minRecommendedVersion": 110,
        "minRequiredVersion": 100,
        "anonymizePersonalData": true,
        "quickAccessButtons": ["NEWINTHEAPP", "SENDMONEY", "SEARCHTRANSACTIONS"]
    }""".trimIndent(),
    """{
        "deviceId": "987f6543-a21b-45c8-b123-98765ef4321a",
        "primaryUserName": "testUser456",
        "accountSorting": "ACCOUNTTYPE",
        "autoUpdateBalance": false,
        "appId": 101,
        "appLanguage": "fr-FR",
        "maxSessionDuration": 7200,
        "appTheme": "SYSTEM",
        "appVariant": "enterprise",
        "appVersion": 200,
        "appLoginMode": "BIOMETRIC",
        "allowFirebaseTracking": true,
        "deviceModel": "SuperPhone Y900",
        "deviceTheme": "DARK",
        "otherRedApps": ["SuperAppA", "SuperAppB"],
        "osVersion": "FantasticOS 22.1",
        "physicalDeviceId": "098765abcd4321",
        "systemLanguage": "es-ES",
        "incomeExpenseWidgetVariant": false,
        "offerAroundTheProperty": true,
        "offerClick2Credit": false,
        "offerMoneyBoxFieldTesting": true,
        "offerPrivateBanking": true,
        "requireReviewPersonalData": false,
        "requireTermsConditionsAgreement": true,
        "sendDynatraceBeacons": true,
        "allowAccountAlarmNotifications": false,
        "allowIndividualOffersNotifications": false,
        "allowNotificationBadge": true,
        "allowSystemNotifications": false,
        "lastPingNotificationReceivedDateTime": "2024-11-10T15:30:00",
        "pushToken": "samplePushToken_45678",
        "fullAppStartsMsSinceLastCommit": 150000,
        "fullAppStartsSinceLastCommit": 20,
        "lastLoginDateTime": "2024-11-12T14:00:00",
        "numberOfMbfAccounts": 5,
        "numberOfMkaAccounts": 2,
        "numberOfOtherAccounts": 3,
        "numberOfSavingBanks": 3,
        "numberOfSavingBanksAccounts": 8,
        "subsequentAppStartsMsSinceLastCommit": 25000,
        "subsequentAppStartsSinceLastCommit": 10,
        "frequentlyUsedFeatures": ["PHOTO_TRANSFER", "BACKUP", "LOGOFF"],
        "featuresRequiringAttention": ["REVIEW", "INDIVIDUALIZE_DASHBOARD"],
        "subscribedToAloha": false,
        "subscribedToBudgetBook": true,
        "subscribedToDiamond": false,
        "subscribedToKwitt": true,
        "subscribedToWero": false,
        "minRecommendedVersion": 150,
        "minRequiredVersion": 130,
        "anonymizePersonalData": false,
        "quickAccessButtons": ["SENDMONEY", "REQUESTMONEY", "SEARCHTRANSACTIONS"]
    }""".trimIndent(),
    """
    {
        "deviceId": "123e4567-e89b-12d3-a456-426614174000",
        "primaryUserName": "userAlpha",
        "accountSorting": "ACCOUNTHOLDER",
        "autoUpdateBalance": true,
        "appId": 202,
        "appLanguage": "en-GB",
        "maxSessionDuration": 3600,
        "appTheme": "LIGHT",
        "appVariant": "standard",
        "appVersion": 105,
        "appLoginMode": "PASSWORD",
        "allowFirebaseTracking": false,
        "deviceModel": "FuturePhone Z1",
        "deviceTheme": "LIGHT",
        "otherRedApps": ["AppX", "AppY", "AppZ"],
        "osVersion": "FutureOS 10",
        "physicalDeviceId": "abc123xyz098",
        "systemLanguage": "de-DE",
        "incomeExpenseWidgetVariant": true,
        "offerAroundTheProperty": false,
        "offerClick2Credit": true,
        "offerMoneyBoxFieldTesting": false,
        "offerPrivateBanking": true,
        "requireReviewPersonalData": true,
        "requireTermsConditionsAgreement": true,
        "sendDynatraceBeacons": false,
        "allowAccountAlarmNotifications": true,
        "allowIndividualOffersNotifications": true,
        "allowNotificationBadge": true,
        "allowSystemNotifications": true,
        "lastPingNotificationReceivedDateTime": "2024-11-12T12:00:00",
        "pushToken": "pushTokenExample123",
        "fullAppStartsMsSinceLastCommit": 50000,
        "fullAppStartsSinceLastCommit": 15,
        "lastLoginDateTime": "2024-11-11T08:45:00",
        "numberOfMbfAccounts": 7,
        "numberOfMkaAccounts": 1,
        "numberOfOtherAccounts": 0,
        "numberOfSavingBanks": 2,
        "numberOfSavingBanksAccounts": 4,
        "subsequentAppStartsMsSinceLastCommit": 30000,
        "subsequentAppStartsSinceLastCommit": 8,
        "frequentlyUsedFeatures": ["PFM", "PHOTO_TRANSFER"],
        "featuresRequiringAttention": ["LOGOFF"],
        "subscribedToAloha": true,
        "subscribedToBudgetBook": false,
        "subscribedToDiamond": true,
        "subscribedToKwitt": false,
        "subscribedToWero": true,
        "minRecommendedVersion": 140,
        "minRequiredVersion": 120,
        "anonymizePersonalData": true,
        "quickAccessButtons": ["APPLEPAY", "SINVEST", "BRANCHLOCATOR"]
    }
    """.trimIndent(),
    """
    {
        "deviceId": "999e4567-e89b-12d3-a456-426614174999",
        "primaryUserName": "userBeta",
        "accountSorting": "ACCOUNTTYPE",
        "autoUpdateBalance": false,
        "appId": 303,
        "appLanguage": "es-ES",
        "maxSessionDuration": 1800,
        "appTheme": "DARK",
        "appVariant": "beta",
        "appVersion": 110,
        "appLoginMode": "BIOMETRIC",
        "allowFirebaseTracking": true,
        "deviceModel": "NextGen Ultra",
        "deviceTheme": "DARK",
        "otherRedApps": ["AppA", "AppB"],
        "osVersion": "OSX 9.5",
        "physicalDeviceId": "xyz456def321",
        "systemLanguage": "en-US",
        "incomeExpenseWidgetVariant": false,
        "offerAroundTheProperty": true,
        "offerClick2Credit": false,
        "offerMoneyBoxFieldTesting": true,
        "offerPrivateBanking": false,
        "requireReviewPersonalData": false,
        "requireTermsConditionsAgreement": true,
        "sendDynatraceBeacons": true,
        "allowAccountAlarmNotifications": false,
        "allowIndividualOffersNotifications": false,
        "allowNotificationBadge": true,
        "allowSystemNotifications": false,
        "lastPingNotificationReceivedDateTime": "2024-11-10T16:30:00",
        "pushToken": "pushTokenExample456",
        "fullAppStartsMsSinceLastCommit": 40000,
        "fullAppStartsSinceLastCommit": 10,
        "lastLoginDateTime": "2024-11-09T14:30:00",
        "numberOfMbfAccounts": 2,
        "numberOfMkaAccounts": 3,
        "numberOfOtherAccounts": 1,
        "numberOfSavingBanks": 1,
        "numberOfSavingBanksAccounts": 2,
        "subsequentAppStartsMsSinceLastCommit": 20000,
        "subsequentAppStartsSinceLastCommit": 5,
        "frequentlyUsedFeatures": ["INCOGNITO", "BACKUP"],
        "featuresRequiringAttention": ["PHOTO_TRANSFER"],
        "subscribedToAloha": false,
        "subscribedToBudgetBook": true,
        "subscribedToDiamond": false,
        "subscribedToKwitt": true,
        "subscribedToWero": false,
        "minRecommendedVersion": 130,
        "minRequiredVersion": 100,
        "anonymizePersonalData": false,
        "quickAccessButtons": ["SEARCHTRANSACTIONS", "SERVICECENTER"]
    }
    """.trimIndent(),
    """
    {
        "deviceId": "888e4567-e89b-12d3-a456-426614174888",
        "primaryUserName": "userGamma",
        "accountSorting": "ACCOUNTHOLDER",
        "autoUpdateBalance": true,
        "appId": 404,
        "appLanguage": "fr-FR",
        "maxSessionDuration": 5400,
        "appTheme": "SYSTEM",
        "appVariant": "alpha",
        "appVersion": 200,
        "appLoginMode": "PASSWORD",
        "allowFirebaseTracking": true,
        "deviceModel": "Device Pro Max",
        "deviceTheme": "SYSTEM",
        "otherRedApps": ["AppP", "AppQ", "AppR"],
        "osVersion": "MobileOS 3.1",
        "physicalDeviceId": "lmn789ghi654",
        "systemLanguage": "it-IT",
        "incomeExpenseWidgetVariant": true,
        "offerAroundTheProperty": true,
        "offerClick2Credit": false,
        "offerMoneyBoxFieldTesting": true,
        "offerPrivateBanking": true,
        "requireReviewPersonalData": true,
        "requireTermsConditionsAgreement": false,
        "sendDynatraceBeacons": true,
        "allowAccountAlarmNotifications": true,
        "allowIndividualOffersNotifications": true,
        "allowNotificationBadge": true,
        "allowSystemNotifications": true,
        "lastPingNotificationReceivedDateTime": "2024-11-12T20:15:00",
        "pushToken": "pushTokenExample789",
        "fullAppStartsMsSinceLastCommit": 60000,
        "fullAppStartsSinceLastCommit": 20,
        "lastLoginDateTime": "2024-11-11T10:00:00",
        "numberOfMbfAccounts": 5,
        "numberOfMkaAccounts": 2,
        "numberOfOtherAccounts": 3,
        "numberOfSavingBanks": 3,
        "numberOfSavingBanksAccounts": 6,
        "subsequentAppStartsMsSinceLastCommit": 45000,
        "subsequentAppStartsSinceLastCommit": 12,
        "frequentlyUsedFeatures": ["CHARGE_PHONE", "BACKUP", "LOGOFF"],
        "featuresRequiringAttention": ["REVIEW"],
        "subscribedToAloha": true,
        "subscribedToBudgetBook": false,
        "subscribedToDiamond": true,
        "subscribedToKwitt": true,
        "subscribedToWero": true,
        "minRecommendedVersion": 150,
        "minRequiredVersion": 130,
        "anonymizePersonalData": true,
        "quickAccessButtons": ["SENDMONEY", "MAILBOX", "CARDBLOCKING"]
    }
    """.trimIndent()
)
